<?php
define("DB_TABLO","duyuru");
define("DB_TABLO_ID","id");
define("DB_TABLO_MESAJ","mesaj");
define("DB_TABLO_TARIH","tarih");
define("DB_TABLO_YAZAR","yazar");
define("DB_TABLO_LINK","link");
define("DB_HOST","localhost");
define("DB_KULLANICI","forgamep_kmyo");
define("DB_SIFRE","Kmyo_?123");
define("DB_VERITABANI","forgamep_myo");
?>